#!/usr/bin/python

import os

install_dir = '/tmp/SConsInstaller'

# Run the normal SCons install process
if os.system('cd %s && python setup.py install' % install_dir) != 0:
    exit(1)

# Remove SCons source files now that it has been installed on the target system
os.system('rm -rf %s' % install_dir)
